package com.my6225.fall2018.courseservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="announcementsDB")
public class Announcements {
	
	private String id;
	private long announcementID;
	private String announcementText;
	private String boardID;

	public Announcements() {
		// TODO Auto-generated constructor stub
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "announcementID")
	public long getAnnouncementID() {
		return announcementID;
	}
	public void setAnnouncementID(long announcementID) {
		this.announcementID = announcementID;
	}

	@DynamoDBAttribute(attributeName="announcementText")
	public String getAnnouncementText() {
		return announcementText;
	}
	public void setAnnouncementText(String announcementText) {
		if (announcementText.length() <= 160) {
			this.announcementText = announcementText;
		}
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "boardID")
	public String getBoardID() {
		return boardID;
	}
	public void setBoardID(String boardID) {
		this.boardID = boardID;
	}
}
