package com.my6225.fall2018.courseservice.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="courseDB")
public class Course {
	
	private String id;
	private String title;
	private long courseID;
	private String professorID;
	private String taID;
	private String department;
	private String boardID;
	private List<String> roster;

	public Course() {
		// TODO Auto-generated constructor stub
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "courseID")
	public long getCourseID() {
		return courseID;
	}
	public void setCourseID(long courseID) {
		this.courseID = courseID;
	}
	
	@DynamoDBAttribute(attributeName="title")
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute(attributeName="professorID")
	public String getProfessorID() {
		return professorID;
	}
	public void setProfessorID(String professorID) {
		this.professorID = professorID;
	}

	@DynamoDBAttribute(attributeName="taID")
	public String getTaID() {
		return taID;
	}
	public void setTaID(String taID) {
		this.taID = taID;
	}

	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}

	@DynamoDBAttribute(attributeName="boardID")
	public String getBoardID() {
		return boardID;
	}
	public void setBoardID(String boardID) {
		this.boardID = boardID;
	}

	@DynamoDBAttribute(attributeName="roster")	
	public List<String> getRoster() {
		return roster;
	}
	public void setRoster(List<String> roster) {
		this.roster = roster;
	}

}
